import fs from "node:fs/promises";
import path from "node:path";

type ResourceSeed = {
  slug: string;
  title: string;
  description: string;
  authors: string[];
  link: string;
  createdAt: string; // YYYY-MM-DD
  tags: string[];
  image?: string;
};

const OUT_DIR = path.join(process.cwd(), "src", "content", "resources");

function fmEscape(value: string) {
  // safe single-line YAML string
  const v = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  return `"${v}"`;
}

function toFrontmatter(r: ResourceSeed) {
  const lines: string[] = [];
  lines.push("---");
  lines.push(`title: ${fmEscape(r.title)}`);
  lines.push(`description: ${fmEscape(r.description)}`);
  lines.push(`authors: [${r.authors.map(fmEscape).join(", ")}]`);
  lines.push(`link: ${fmEscape(r.link)}`);
  lines.push(`createdAt: ${fmEscape(r.createdAt)}`);
  if (r.image) lines.push(`image: ${fmEscape(r.image)}`);
  lines.push(`tags: [${r.tags.map(fmEscape).join(", ")}]`);
  lines.push("---");
  return lines.join("\n");
}

const SEED: ResourceSeed[] = [
  {
    slug: "gnu-project",
    title: "GNU Project",
    description: "Proyecto fundacional del software libre; herramientas, licencias y comunidad.",
    authors: ["Richard Stallman", "Free Software Foundation"],
    link: "https://www.gnu.org/",
    createdAt: "1983-09-27",
    tags: ["open-source", "software-libre", "historia", "comunidad"],
  },
  {
    slug: "free-software-foundation",
    title: "Free Software Foundation (FSF)",
    description: "Organizacion que promueve y defiende el software libre y las cuatro libertades.",
    authors: ["Free Software Foundation"],
    link: "https://www.fsf.org/",
    createdAt: "1985-10-04",
    tags: ["open-source", "software-libre", "democracia", "comunidad"],
  },
  {
    slug: "gnu-general-public-license",
    title: "GNU General Public License (GPL)",
    description: "Licencia copyleft clave para cooperacion y distribucion del software.",
    authors: ["Free Software Foundation"],
    link: "https://www.gnu.org/licenses/gpl-3.0.en.html",
    createdAt: "2007-06-29",
    tags: ["open-source", "licencias", "cooperacion", "derechos"],
  },
  {
    slug: "creative-commons",
    title: "Creative Commons",
    description: "Licencias para compartir cultura y conocimiento; puente entre arte y acceso.",
    authors: ["Creative Commons"],
    link: "https://creativecommons.org/",
    createdAt: "2001-01-01",
    tags: ["arte", "comunidad", "licencias", "cultura-libre"],
  },
  {
    slug: "wikipedia",
    title: "Wikipedia",
    description: "Enciclopedia libre colaborativa; infraestructura social de conocimiento compartido.",
    authors: ["Wikimedia Foundation", "Comunidad Wikipedia"],
    link: "https://www.wikipedia.org/",
    createdAt: "2001-01-15",
    tags: ["comunidad", "conocimiento", "cooperacion", "open-source"],
  },
  {
    slug: "openstreetmap",
    title: "OpenStreetMap",
    description: "Mapa libre del mundo creado por voluntaries; datos abiertos para la comunidad.",
    authors: ["OpenStreetMap Foundation", "Comunidad OSM"],
    link: "https://www.openstreetmap.org/",
    createdAt: "2004-08-09",
    tags: ["datos-abiertos", "comunidad", "cooperacion", "herramientas"],
  },
  {
    slug: "debian",
    title: "Debian",
    description: "Distribucion comunitaria que prioriza libertad, estabilidad y procesos transparentes.",
    authors: ["Debian Project"],
    link: "https://www.debian.org/",
    createdAt: "1993-08-16",
    tags: ["open-source", "comunidad", "infraestructura", "linux"],
  },
  {
    slug: "linux-kernel",
    title: "Linux Kernel",
    description: "Nucleo de sistema operativo desarrollado de forma colaborativa a escala planetaria.",
    authors: ["Linus Torvalds", "Comunidad Linux"],
    link: "https://www.kernel.org/",
    createdAt: "1991-09-17",
    tags: ["open-source", "historia", "infraestructura", "linux"],
  },
  {
    slug: "git",
    title: "Git",
    description: "Control de versiones distribuido; herramienta de cooperacion y trazabilidad.",
    authors: ["Linus Torvalds", "Comunidad Git"],
    link: "https://git-scm.com/",
    createdAt: "2005-04-07",
    tags: ["open-source", "herramientas", "cooperacion", "infraestructura"],
  },
  {
    slug: "tor",
    title: "Tor Project",
    description: "Herramientas para privacidad y libertad de comunicacion en redes.",
    authors: ["Tor Project"],
    link: "https://www.torproject.org/",
    createdAt: "2002-01-01",
    tags: ["privacidad", "derechos", "comunidad", "software-libre"],
  },
  {
    slug: "signal",
    title: "Signal",
    description: "Mensajeria privada con cifrado de extremo a extremo; enfoque en derechos digitales.",
    authors: ["Signal Foundation"],
    link: "https://signal.org/",
    createdAt: "2014-07-29",
    tags: ["privacidad", "derechos", "comunidad", "herramientas"],
  },
  {
    slug: "matrix",
    title: "Matrix",
    description: "Protocolo abierto para comunicacion descentralizada y federada.",
    authors: ["The Matrix.org Foundation"],
    link: "https://matrix.org/",
    createdAt: "2014-02-01",
    tags: ["descentralizacion", "open-source", "comunidad", "protocolos"],
  },
  {
    slug: "mastodon",
    title: "Mastodon",
    description: "Red social federada; alternativa comunitaria a plataformas centralizadas.",
    authors: ["Eugen Rochko", "Comunidad Mastodon"],
    link: "https://joinmastodon.org/",
    createdAt: "2016-03-01",
    tags: ["descentralizacion", "comunidad", "redes", "open-source"],
  },
  {
    slug: "activitypub",
    title: "ActivityPub",
    description: "Estandar abierto para redes sociales federadas (el 'correo' de lo social).",
    authors: ["W3C Social Web Working Group"],
    link: "https://www.w3.org/TR/activitypub/",
    createdAt: "2018-01-23",
    tags: ["protocolos", "descentralizacion", "redes", "estandares"],
  },
  {
    slug: "internet-archive",
    title: "Internet Archive",
    description: "Archivo digital de la web y medios; memoria colectiva y acceso publico.",
    authors: ["Internet Archive"],
    link: "https://archive.org/",
    createdAt: "1996-01-01",
    tags: ["archivo", "conocimiento", "comunidad", "historia"],
  },
  {
    slug: "public-library-memory-of-the-world",
    title: "Public Library / Memory of the World",
    description: "Proyectos artistico-politicos sobre bibliotecas, acceso y conocimiento comun.",
    authors: ["Marcell Mars", "Tomislav Medak", "Comunidad"],
    link: "https://memoryoftheworld.org/",
    createdAt: "2012-01-01",
    tags: ["arte", "conocimiento", "comunidad", "bibliotecas"],
  },
  {
    slug: "calibre",
    title: "Calibre",
    description: "Gestion de bibliotecas digitales; herramienta para organizar libros y formatos.",
    authors: ["Kovid Goyal", "Comunidad Calibre"],
    link: "https://calibre-ebook.com/",
    createdAt: "2006-10-31",
    tags: ["herramientas", "open-source", "bibliotecas", "conocimiento"],
  },
  {
    slug: "blender",
    title: "Blender",
    description: "Suite libre para 3D; puente entre arte, comunidad y herramientas abiertas.",
    authors: ["Blender Foundation", "Comunidad Blender"],
    link: "https://www.blender.org/",
    createdAt: "2002-01-01",
    tags: ["arte", "open-source", "herramientas", "comunidad"],
  },
  {
    slug: "krita",
    title: "Krita",
    description: "Pintura digital libre; herramienta artistica comunitaria.",
    authors: ["Krita Foundation", "Comunidad Krita"],
    link: "https://krita.org/",
    createdAt: "2005-01-01",
    tags: ["arte", "open-source", "herramientas", "comunidad"],
  },
  {
    slug: "gimp",
    title: "GIMP",
    description: "Edicion de imagen libre; historia larga del ecosistema de herramientas abiertas.",
    authors: ["GIMP Development Team"],
    link: "https://www.gimp.org/",
    createdAt: "1996-02-15",
    tags: ["open-source", "herramientas", "arte", "historia"],
  },
  {
    slug: "inkscape",
    title: "Inkscape",
    description: "Editor vectorial libre; util para grafica, diagramas y publicaciones.",
    authors: ["Inkscape Project"],
    link: "https://inkscape.org/",
    createdAt: "2003-01-01",
    tags: ["open-source", "herramientas", "arte", "comunidad"],
  },
  {
    slug: "audacity",
    title: "Audacity",
    description: "Edicion de audio libre; herramienta comun para produccion comunitaria.",
    authors: ["Audacity Team"],
    link: "https://www.audacityteam.org/",
    createdAt: "2000-05-28",
    tags: ["open-source", "herramientas", "audio", "comunidad"],
  },
  {
    slug: "lmms",
    title: "LMMS",
    description: "Produccion musical libre; alternativa comunitaria para crear sonidos.",
    authors: ["LMMS Developers"],
    link: "https://lmms.io/",
    createdAt: "2004-01-01",
    tags: ["open-source", "audio", "herramientas", "arte"],
  },
  {
    slug: "pure-data",
    title: "Pure Data (Pd)",
    description: "Programacion visual para audio y multimedia; cultura DIY y experimentacion.",
    authors: ["Miller Puckette", "Comunidad Pd"],
    link: "https://puredata.info/",
    createdAt: "1996-01-01",
    tags: ["audio", "diy", "arte", "herramientas"],
  },
  {
    slug: "processing",
    title: "Processing",
    description: "Entorno para arte generativo y aprendizaje; comunidad y creatividad.",
    authors: ["Casey Reas", "Ben Fry", "Processing Foundation"],
    link: "https://processing.org/",
    createdAt: "2001-01-01",
    tags: ["arte", "herramientas", "educacion", "comunidad"],
  },
  {
    slug: "p5js",
    title: "p5.js",
    description: "Biblioteca JS para arte y educacion creativa; accesible y comunitaria.",
    authors: ["Processing Foundation", "Lauren McCarthy", "Comunidad p5.js"],
    link: "https://p5js.org/",
    createdAt: "2013-01-01",
    tags: ["arte", "educacion", "herramientas", "comunidad"],
  },
  {
    slug: "arduino",
    title: "Arduino",
    description: "Plataforma de hardware y software para prototipado; cultura maker y DIY.",
    authors: ["Arduino"],
    link: "https://www.arduino.cc/",
    createdAt: "2005-01-01",
    tags: ["hardware", "diy", "herramientas", "educacion"],
  },
  {
    slug: "raspberry-pi",
    title: "Raspberry Pi",
    description: "Computadoras accesibles para educacion, hackerspaces y proyectos comunitarios.",
    authors: ["Raspberry Pi Foundation"],
    link: "https://www.raspberrypi.com/",
    createdAt: "2012-02-29",
    tags: ["hardware", "educacion", "diy", "herramientas"],
  },
  {
    slug: "open-hardware-definition",
    title: "Open Source Hardware Definition",
    description: "Definicion comunitaria de hardware abierto; licencias y principios.",
    authors: ["OSHWA"],
    link: "https://www.oshwa.org/definition/",
    createdAt: "2010-01-01",
    tags: ["hardware", "open-source", "licencias", "comunidad"],
  },
  {
    slug: "wikihouse",
    title: "WikiHouse",
    description: "Arquitectura abierta y modular; DIY y comunidad para construir en comun.",
    authors: ["WikiHouse Foundation", "Comunidad"],
    link: "https://www.wikihouse.cc/",
    createdAt: "2011-01-01",
    tags: ["diy", "comunidad", "herramientas", "arquitectura"],
  },
  {
    slug: "right-to-repair",
    title: "Right to Repair",
    description: "Movimiento por el derecho a reparar; contra la obsolescencia y por autonomia.",
    authors: ["Movimiento global"],
    link: "https://repair.org/",
    createdAt: "2012-01-01",
    tags: ["diy", "derechos", "hardware", "comunidad"],
  },
  {
    slug: "ifixit",
    title: "iFixit",
    description: "Guias de reparacion y cultura de mantenimiento; conocimiento practico abierto.",
    authors: ["iFixit"],
    link: "https://www.ifixit.com/",
    createdAt: "2003-01-01",
    tags: ["diy", "hardware", "conocimiento", "herramientas"],
  },
  {
    slug: "sci-hub",
    title: "Sci-Hub (debate sobre acceso)",
    description:
      "Nodo polemico sobre acceso a articulos academicos; sirve para pensar infraestructura y desigualdad.",
    authors: ["Alexandra Elbakyan"],
    link: "https://sci-hub.se/",
    createdAt: "2011-09-05",
    tags: ["conocimiento", "archivo", "politica", "debate"],
  },
  {
    slug: "libgen",
    title: "Library Genesis (debate sobre bibliotecas)",
    description: "Archivo no-oficial de libros; tension entre acceso, legalidad y comunidad.",
    authors: ["Comunidad"],
    link: "https://libgen.is/",
    createdAt: "2008-01-01",
    tags: ["bibliotecas", "archivo", "debate", "conocimiento"],
  },
  {
    slug: "creativecommons-public-domain-mark",
    title: "CC Public Domain Mark",
    description: "Etiqueta para obras en dominio publico; facilita reuso cultural.",
    authors: ["Creative Commons"],
    link: "https://creativecommons.org/publicdomain/mark/1.0/",
    createdAt: "2010-01-01",
    tags: ["cultura-libre", "licencias", "arte", "conocimiento"],
  },
  {
    slug: "creative-commons-licenses",
    title: "Creative Commons Licenses",
    description: "Set de licencias para compartir obras bajo condiciones claras.",
    authors: ["Creative Commons"],
    link: "https://creativecommons.org/licenses/",
    createdAt: "2002-12-16",
    tags: ["licencias", "arte", "comunidad", "cultura-libre"],
  },
  {
    slug: "soldering-is-easy",
    title: "Soldering Is Easy",
    description: "Historieta/guia DIY para aprender a soldar; pedagogia accesible.",
    authors: ["Mitch Altman", "Andie Nordgren", "Jeff Keyzer"],
    link: "https://mightyohm.com/blog/2011/04/soldering-is-easy-comic-book/",
    createdAt: "2011-04-01",
    tags: ["diy", "hardware", "educacion", "comic"],
  },
  {
    slug: "low-tech-magazine",
    title: "Low-tech Magazine",
    description: "Critica tecnologica y energia; perspectivas sobre progreso y limites materiales.",
    authors: ["Kris De Decker"],
    link: "https://www.lowtechmagazine.com/",
    createdAt: "2007-01-01",
    tags: ["teoria", "energia", "progreso", "critica"],
  },
  {
    slug: "the-cathedral-and-the-bazaar",
    title: "The Cathedral and the Bazaar",
    description: "Ensayo sobre modelos de desarrollo abierto y coordinacion comunitaria.",
    authors: ["Eric S. Raymond"],
    link: "https://www.catb.org/~esr/writings/cathedral-bazaar/",
    createdAt: "1997-01-01",
    tags: ["open-source", "teoria", "historia", "cooperacion"],
  },
  {
    slug: "commons-by-elionor-ostrom",
    title: "Governing the Commons",
    description: "Teoria sobre gestion comunitaria de bienes comunes; base para pensar infraestructuras.",
    authors: ["Elinor Ostrom"],
    link: "https://press.princeton.edu/books/paperback/9780521405997/governing-the-commons",
    createdAt: "1990-01-01",
    tags: ["comunes", "teoria", "comunidad", "democracia"],
  },
  {
    slug: "mutual-aid",
    title: "Mutual Aid: A Factor of Evolution",
    description: "Texto clasico sobre ayuda mutua; genealogia de cooperacion y comunidad.",
    authors: ["Peter Kropotkin"],
    link: "https://en.wikipedia.org/wiki/Mutual_Aid:_A_Factor_of_Evolution",
    createdAt: "1902-01-01",
    tags: ["ayuda-mutua", "teoria", "comunidad", "historia"],
  },
  {
    slug: "design-justice-network",
    title: "Design Justice Network",
    description: "Principios para diseño centrado en comunidades; justicia, inclusion y poder.",
    authors: ["Design Justice Network"],
    link: "https://designjustice.org/",
    createdAt: "2016-01-01",
    tags: ["democracia", "comunidad", "diseno", "justicia"],
  },
  {
    slug: "federated-wiki",
    title: "Federated Wiki",
    description: "Wiki federada; experimentos sobre autoría distribuida y redes de conocimiento.",
    authors: ["Ward Cunningham", "Comunidad"],
    link: "https://fed.wiki.org/",
    createdAt: "2011-01-01",
    tags: ["descentralizacion", "conocimiento", "herramientas", "wikis"],
  },
  {
    slug: "tiddlywiki",
    title: "TiddlyWiki",
    description: "Wiki de un solo archivo; pensamiento modular y portabilidad.",
    authors: ["Jeremy Ruston", "Comunidad TiddlyWiki"],
    link: "https://tiddlywiki.com/",
    createdAt: "2004-01-01",
    tags: ["conocimiento", "herramientas", "wikis", "diy"],
  },
  {
    slug: "zotero",
    title: "Zotero",
    description: "Gestion de referencias y bibliografia; herramienta comunitaria para investigacion.",
    authors: ["Corporation for Digital Scholarship"],
    link: "https://www.zotero.org/",
    createdAt: "2006-10-05",
    tags: ["conocimiento", "herramientas", "bibliotecas", "comunidad"],
  },
  {
    slug: "arxiv",
    title: "arXiv",
    description: "Repositorio abierto de preprints; infraestructura para circulacion del conocimiento.",
    authors: ["Cornell University"],
    link: "https://arxiv.org/",
    createdAt: "1991-08-14",
    tags: ["conocimiento", "archivo", "ciencia-abierta", "infraestructura"],
  },
  {
    slug: "open-access-week",
    title: "Open Access Week",
    description: "Semana global para promover acceso abierto y ciencia abierta.",
    authors: ["SPARC", "Comunidad"],
    link: "https://www.openaccessweek.org/",
    createdAt: "2008-01-01",
    tags: ["ciencia-abierta", "comunidad", "conocimiento", "eventos"],
  },
  {
    slug: "mozilla",
    title: "Mozilla",
    description: "Organizacion por una web abierta; herramientas, estandares y comunidad.",
    authors: ["Mozilla Foundation", "Mozilla Corporation"],
    link: "https://www.mozilla.org/",
    createdAt: "1998-03-31",
    tags: ["open-web", "comunidad", "infraestructura", "open-source"],
  },
  {
    slug: "w3c",
    title: "W3C",
    description: "Consorcio de estandares web; gobernanza tecnica y coordinacion.",
    authors: ["World Wide Web Consortium"],
    link: "https://www.w3.org/",
    createdAt: "1994-10-01",
    tags: ["estandares", "open-web", "infraestructura", "comunidad"],
  },
  {
    slug: "creativecommons-open-education",
    title: "Open Education (OER)",
    description: "Recursos educativos abiertos; pedagogia como bien comun.",
    authors: ["Comunidad OER"],
    link: "https://en.wikipedia.org/wiki/Open_educational_resources",
    createdAt: "2002-01-01",
    tags: ["educacion", "comunes", "conocimiento", "cultura-libre"],
  },
  {
    slug: "linux-from-scratch",
    title: "Linux From Scratch",
    description: "Guia para construir un sistema Linux desde cero; aprendizaje profundo y DIY.",
    authors: ["Gerard Beekmans", "Comunidad LFS"],
    link: "https://www.linuxfromscratch.org/",
    createdAt: "1999-01-01",
    tags: ["linux", "educacion", "diy", "herramientas"],
  },
  {
    slug: "gentoo",
    title: "Gentoo Linux",
    description: "Distribucion orientada a construccion y optimizacion; comunidad y aprendizaje.",
    authors: ["Gentoo Foundation", "Comunidad Gentoo"],
    link: "https://www.gentoo.org/",
    createdAt: "2000-01-01",
    tags: ["linux", "open-source", "comunidad", "educacion"],
  },
  {
    slug: "arch-linux",
    title: "Arch Linux",
    description: "Distribucion minimalista con filosofia KISS; cultura de documentacion comunitaria.",
    authors: ["Arch Linux Project"],
    link: "https://archlinux.org/",
    createdAt: "2002-03-11",
    tags: ["linux", "comunidad", "infraestructura", "open-source"],
  },
  {
    slug: "arch-wiki",
    title: "ArchWiki",
    description: "Documentacion tecnica comunitaria ampliamente reutilizada; conocimiento practico.",
    authors: ["Comunidad Arch Linux"],
    link: "https://wiki.archlinux.org/",
    createdAt: "2003-01-01",
    tags: ["conocimiento", "comunidad", "wikis", "infraestructura"],
  },
  {
    slug: "openbsd",
    title: "OpenBSD",
    description: "Sistema centrado en seguridad y calidad; cultura de simplicidad y auditoria.",
    authors: ["OpenBSD Project"],
    link: "https://www.openbsd.org/",
    createdAt: "1995-10-18",
    tags: ["open-source", "infraestructura", "seguridad", "comunidad"],
  },
  {
    slug: "openzfs",
    title: "OpenZFS",
    description: "Sistema de archivos avanzado; infraestructura y resiliencia como valores.",
    authors: ["OpenZFS Community"],
    link: "https://openzfs.org/",
    createdAt: "2013-01-01",
    tags: ["infraestructura", "open-source", "comunidad", "resiliencia"],
  },
  {
    slug: "borg-backup",
    title: "BorgBackup",
    description: "Backups deduplicados y verificados; cuidado y mantenimiento como practica.",
    authors: ["BorgBackup Authors"],
    link: "https://www.borgbackup.org/",
    createdAt: "2015-01-01",
    tags: ["herramientas", "resiliencia", "infraestructura", "open-source"],
  },
  {
    slug: "syncthing",
    title: "Syncthing",
    description: "Sincronizacion P2P; datos bajo control propio en red.",
    authors: ["Syncthing Community"],
    link: "https://syncthing.net/",
    createdAt: "2013-01-01",
    tags: ["descentralizacion", "herramientas", "privacidad", "open-source"],
  },
  {
    slug: "nextcloud",
    title: "Nextcloud",
    description: "Nube auto-alojada; cooperacion y soberania tecnologica.",
    authors: ["Nextcloud GmbH", "Comunidad Nextcloud"],
    link: "https://nextcloud.com/",
    createdAt: "2016-01-01",
    tags: ["autohosting", "comunidad", "herramientas", "open-source"],
  },
  {
    slug: "home-assistant",
    title: "Home Assistant",
    description: "Automatizacion del hogar local y extensible; alternativa a plataformas cerradas.",
    authors: ["Home Assistant Community"],
    link: "https://www.home-assistant.io/",
    createdAt: "2013-09-17",
    tags: ["diy", "autohosting", "herramientas", "open-source"],
  },
  {
    slug: "open-wrt",
    title: "OpenWrt",
    description: "Firmware libre para routers; control comunitario de infraestructura domestica.",
    authors: ["OpenWrt Project"],
    link: "https://openwrt.org/",
    createdAt: "2004-01-01",
    tags: ["infraestructura", "open-source", "hardware", "comunidad"],
  },
  {
    slug: "diaspora",
    title: "Diaspora*",
    description: "Red social descentralizada temprana; historia de alternativas a plataformas.",
    authors: ["Diaspora community"],
    link: "https://diasporafoundation.org/",
    createdAt: "2010-01-01",
    tags: ["descentralizacion", "redes", "historia", "comunidad"],
  },
  {
    slug: "scuttlebutt",
    title: "Secure Scuttlebutt (SSB)",
    description: "Red social P2P offline-friendly; comunidad y experimentos de confianza.",
    authors: ["SSB Community"],
    link: "https://scuttlebutt.nz/",
    createdAt: "2014-01-01",
    tags: ["descentralizacion", "redes", "p2p", "comunidad"],
  },
  {
    slug: "ipfs",
    title: "IPFS",
    description: "Sistema de archivos distribuido; pensar archivos y memoria en red.",
    authors: ["Protocol Labs"],
    link: "https://ipfs.tech/",
    createdAt: "2015-02-01",
    tags: ["p2p", "infraestructura", "archivo", "descentralizacion"],
  },
  {
    slug: "dat",
    title: "Dat / Hypercore ecosystem",
    description: "Herramientas P2P para compartir datasets y archivos; ciencia abierta y archivos.",
    authors: ["Dat Project", "Hypercore community"],
    link: "https://hypercore-protocol.org/",
    createdAt: "2013-01-01",
    tags: ["p2p", "datos-abiertos", "archivo", "herramientas"],
  },
  {
    slug: "open-data-handbook",
    title: "Open Data Handbook",
    description: "Guia practica para publicar y usar datos abiertos.",
    authors: ["Open Knowledge Foundation"],
    link: "https://opendatahandbook.org/",
    createdAt: "2012-01-01",
    tags: ["datos-abiertos", "conocimiento", "comunidad", "guia"],
  },
  {
    slug: "open-knowledge-foundation",
    title: "Open Knowledge Foundation",
    description: "Organizacion por el conocimiento abierto; datos, comunidades y herramientas.",
    authors: ["Open Knowledge Foundation"],
    link: "https://okfn.org/",
    createdAt: "2004-01-01",
    tags: ["datos-abiertos", "comunidad", "conocimiento", "politica"],
  },
  {
    slug: "open-source-initiative",
    title: "Open Source Initiative (OSI)",
    description: "Organizacion que mantiene la definicion de open source y aprueba licencias.",
    authors: ["Open Source Initiative"],
    link: "https://opensource.org/",
    createdAt: "1998-02-01",
    tags: ["open-source", "licencias", "comunidad", "historia"],
  },
  {
    slug: "open-source-definition",
    title: "Open Source Definition",
    description: "Definicion historica de open source; criterios para licencias y distribucion.",
    authors: ["Open Source Initiative"],
    link: "https://opensource.org/osd",
    createdAt: "1998-01-01",
    tags: ["open-source", "licencias", "teoria", "historia"],
  },
  {
    slug: "permacomputing",
    title: "Permacomputing",
    description: "Practicas de computacion sostenible: reuse, low-tech, cuidado, y limites materiales.",
    authors: ["Permacomputing community"],
    link: "https://permacomputing.net/",
    createdAt: "2020-01-01",
    tags: ["critica", "energia", "diy", "sustentabilidad"],
  },
  {
    slug: "solar-powered-website",
    title: "A Solar Powered Website",
    description: "Sitio low-tech como practica; pensar energia, forma y politica de la web.",
    authors: ["Low-tech Magazine"],
    link: "https://solar.lowtechmagazine.com/",
    createdAt: "2018-01-01",
    tags: ["critica", "energia", "open-web", "diseno"],
  },
  {
    slug: "the-maintainers",
    title: "The Maintainers",
    description: "Red de investigacion sobre mantenimiento; reparar, sostener y cuidar sistemas.",
    authors: ["The Maintainers"],
    link: "https://themaintainers.org/",
    createdAt: "2016-01-01",
    tags: ["mantenimiento", "historia", "teoria", "comunidad"],
  },
  {
    slug: "hackerspaces",
    title: "Hackerspaces (movimiento)",
    description: "Espacios comunitarios para hacer, aprender y compartir herramientas.",
    authors: ["Movimiento global"],
    link: "https://en.wikipedia.org/wiki/Hackerspace",
    createdAt: "2007-01-01",
    tags: ["comunidad", "diy", "meetups", "herramientas"],
  },
  {
    slug: "makerspaces",
    title: "Makerspaces (movimiento)",
    description: "Talleres compartidos; fabrica comunitaria, pedagogia y herramientas.",
    authors: ["Movimiento global"],
    link: "https://en.wikipedia.org/wiki/Makerspace",
    createdAt: "2005-01-01",
    tags: ["comunidad", "diy", "educacion", "herramientas"],
  },
  {
    slug: "civic-tech",
    title: "Civic Tech (campo)",
    description: "Tecnologia para lo publico; transparencia, participacion y herramientas abiertas.",
    authors: ["Comunidad"],
    link: "https://en.wikipedia.org/wiki/Civic_technology",
    createdAt: "2012-01-01",
    tags: ["democracia", "comunidad", "politica", "herramientas"],
  },
  {
    slug: "decidim",
    title: "Decidim",
    description: "Plataforma libre para participacion democratica; procesos y transparencia.",
    authors: ["Decidim community"],
    link: "https://decidim.org/",
    createdAt: "2016-01-01",
    tags: ["democracia", "open-source", "comunidad", "herramientas"],
  },
  {
    slug: "loomio",
    title: "Loomio",
    description: "Herramienta para toma de decisiones colectivas; cooperacion online.",
    authors: ["Loomio Cooperative"],
    link: "https://www.loomio.com/",
    createdAt: "2012-01-01",
    tags: ["democracia", "cooperacion", "herramientas", "comunidad"],
  },
  {
    slug: "coopcycle",
    title: "CoopCycle",
    description: "Plataforma para cooperativas de delivery; tecnologia al servicio de trabajo cooperativo.",
    authors: ["CoopCycle federation"],
    link: "https://coopcycle.org/en/",
    createdAt: "2017-01-01",
    tags: ["cooperativas", "comunidad", "open-source", "economia"],
  },
  {
    slug: "platform-cooperativism",
    title: "Platform Cooperativism",
    description: "Marco teorico y practico sobre plataformas cooperativas y propiedad colectiva.",
    authors: ["Trebor Scholz", "Comunidad"],
    link: "https://platform.coop/",
    createdAt: "2015-01-01",
    tags: ["cooperativas", "teoria", "economia", "comunidad"],
  },
  {
    slug: "creative-coding",
    title: "Creative Coding (campo)",
    description: "Practicas de programacion para arte, aprendizaje y expresion.",
    authors: ["Comunidad"],
    link: "https://en.wikipedia.org/wiki/Creative_coding",
    createdAt: "2000-01-01",
    tags: ["arte", "educacion", "herramientas", "comunidad"],
  },
  {
    slug: "gutenberg",
    title: "Project Gutenberg",
    description: "Biblioteca de libros en dominio publico; archivo de lectura distribuida.",
    authors: ["Project Gutenberg"],
    link: "https://www.gutenberg.org/",
    createdAt: "1971-07-04",
    tags: ["bibliotecas", "archivo", "conocimiento", "dominio-publico"],
  },
  {
    slug: "standard-ebooks",
    title: "Standard Ebooks",
    description: "Ediciones cuidadas de libros en dominio publico; calidad como forma de cuidado.",
    authors: ["Standard Ebooks"],
    link: "https://standardebooks.org/",
    createdAt: "2015-01-01",
    tags: ["bibliotecas", "dominio-publico", "archivo", "cuidado"],
  },
  {
    slug: "open-library",
    title: "Open Library",
    description: "Catalogo abierto de libros; parte de Internet Archive.",
    authors: ["Internet Archive"],
    link: "https://openlibrary.org/",
    createdAt: "2006-01-01",
    tags: ["bibliotecas", "archivo", "conocimiento", "comunidad"],
  },
  {
    slug: "wikisource",
    title: "Wikisource",
    description: "Biblioteca libre de textos; transcripcion y edicion comunitaria.",
    authors: ["Wikimedia Foundation", "Comunidad"],
    link: "https://wikisource.org/",
    createdAt: "2003-11-24",
    tags: ["bibliotecas", "archivo", "comunidad", "conocimiento"],
  },
  {
    slug: "wikidata",
    title: "Wikidata",
    description: "Base de datos abierta y colaborativa; infra para conocimiento estructurado.",
    authors: ["Wikimedia Foundation", "Comunidad"],
    link: "https://www.wikidata.org/",
    createdAt: "2012-10-29",
    tags: ["datos-abiertos", "infraestructura", "conocimiento", "comunidad"],
  },
  {
    slug: "open-source-seeds",
    title: "Open Source Seed Initiative (OSSI)",
    description: "Semillas como bien comun; licencias y autonomia agricola.",
    authors: ["OSSI"],
    link: "https://osseeds.org/",
    createdAt: "2012-01-01",
    tags: ["comunes", "licencias", "diy", "comunidad"],
  },
  {
    slug: "open-source-ecology",
    title: "Open Source Ecology",
    description: "Maquinas abiertas para economias locales; herramientas como comunes.",
    authors: ["Marcin Jakubowski", "Open Source Ecology"],
    link: "https://www.opensourceecology.org/",
    createdAt: "2003-01-01",
    tags: ["hardware", "comunes", "diy", "comunidad"],
  },
  {
    slug: "appropriate-technology",
    title: "Appropriate technology (concepto)",
    description: "Tecnologia apropiada: herramientas situadas, accesibles, y orientadas al bien comun.",
    authors: ["E. F. Schumacher (y campo)"],
    link: "https://en.wikipedia.org/wiki/Appropriate_technology",
    createdAt: "1973-01-01",
    tags: ["teoria", "progreso", "critica", "comunidad"],
  },
  {
    slug: "small-is-beautiful",
    title: "Small Is Beautiful",
    description: "Economia como si la gente importara; critica al crecimiento y a la tecnocracia.",
    authors: ["E. F. Schumacher"],
    link: "https://en.wikipedia.org/wiki/Small_Is_Beautiful",
    createdAt: "1973-01-01",
    tags: ["teoria", "economia", "critica", "comunidad"],
  },
  {
    slug: "the-convivial-tool",
    title: "Tools for Conviviality",
    description: "Herramientas conviviales; pensar tecnologia, poder y autonomia.",
    authors: ["Ivan Illich"],
    link: "https://en.wikipedia.org/wiki/Tools_for_Conviviality",
    createdAt: "1973-01-01",
    tags: ["teoria", "historia", "herramientas", "comunidad"],
  },
  {
    slug: "a-cybernetic-ecology",
    title: "A Cybernetic Ecology",
    description: "Archivo de ecologias ciberneticas; contracultura, sistemas y futuro.",
    authors: ["Stewart Brand (editor)"],
    link: "https://en.wikipedia.org/wiki/Whole_Earth_Catalog",
    createdAt: "1968-01-01",
    tags: ["historia", "teoria", "archivo", "herramientas"],
  },
  {
    slug: "whole-earth-catalog",
    title: "Whole Earth Catalog",
    description: "Catalogo de herramientas, ideas y tecnicas; antecesor cultural de la web.",
    authors: ["Stewart Brand"],
    link: "https://en.wikipedia.org/wiki/Whole_Earth_Catalog",
    createdAt: "1968-01-01",
    tags: ["historia", "herramientas", "archivo", "comunidad"],
  },
  {
    slug: "cybersyn",
    title: "Project Cybersyn (Chile)",
    description: "Experimento de cibernetica y planificacion democratica (1971–1973).",
    authors: ["Stafford Beer", "Equipo Cybersyn"],
    link: "https://en.wikipedia.org/wiki/Project_Cybersyn",
    createdAt: "1971-01-01",
    tags: ["historia", "democracia", "teoria", "latam"],
  },
  {
    slug: "software-freedom-conservancy",
    title: "Software Freedom Conservancy",
    description: "Soporte legal/administrativo para proyectos libres; infraestructura institucional.",
    authors: ["Software Freedom Conservancy"],
    link: "https://sfconservancy.org/",
    createdAt: "2006-01-01",
    tags: ["open-source", "comunidad", "derechos", "infraestructura"],
  },
  {
    slug: "open-collective",
    title: "Open Collective",
    description: "Infraestructura de financiamiento transparente para comunidades y proyectos.",
    authors: ["Open Collective"],
    link: "https://opencollective.com/",
    createdAt: "2016-01-01",
    tags: ["comunidad", "infraestructura", "economia", "transparencia"],
  },
  {
    slug: "kickstarter-critique",
    title: "Plataformas de crowdfunding (tema)",
    description: "Para pensar financiamiento, dependencia y comunidad en proyectos creativos.",
    authors: ["Campo / debate"],
    link: "https://en.wikipedia.org/wiki/Crowdfunding",
    createdAt: "2008-01-01",
    tags: ["economia", "comunidad", "debate", "infraestructura"],
  },
  {
    slug: "foss-licenses-explained",
    title: "Choose an open source license",
    description: "Guia pragmatica para elegir licencias; claridad para cooperacion.",
    authors: ["GitHub"],
    link: "https://choosealicense.com/",
    createdAt: "2013-01-01",
    tags: ["licencias", "open-source", "guia", "comunidad"],
  },
  {
    slug: "open-source-guide",
    title: "Open Source Guides",
    description: "Guias para construir comunidades y proyectos; mantenimiento y procesos.",
    authors: ["GitHub"],
    link: "https://opensource.guide/",
    createdAt: "2017-01-01",
    tags: ["comunidad", "mantenimiento", "open-source", "guia"],
  },
  {
    slug: "code-of-conduct-contributor-covenant",
    title: "Contributor Covenant",
    description: "Codigo de conducta para comunidades; cuidado y limites en proyectos abiertos.",
    authors: ["Coraline Ada Ehmke", "Contributors"],
    link: "https://www.contributor-covenant.org/",
    createdAt: "2014-10-15",
    tags: ["comunidad", "cuidado", "open-source", "convivencia"],
  },
  {
    slug: "internet-health-report",
    title: "Internet Health Report (archivo)",
    description: "Reportes sobre salud de internet; poder, privacidad, inclusion y futuro.",
    authors: ["Mozilla"],
    link: "https://foundation.mozilla.org/en/internet-health-report/",
    createdAt: "2017-01-01",
    tags: ["open-web", "politica", "privacidad", "archivo"],
  },
  {
    slug: "occupy-the-internet-archive",
    title: "Reclamar infraestructuras (tema)",
    description: "Lecturas sobre infraestructuras como comunes: redes, archivos, energia, ciudad.",
    authors: ["Campo / debate"],
    link: "https://en.wikipedia.org/wiki/Infrastructure",
    createdAt: "2010-01-01",
    tags: ["comunes", "teoria", "politica", "infraestructura"],
  },
];

async function main() {
  await fs.mkdir(OUT_DIR, { recursive: true });

  const existing = new Set(await fs.readdir(OUT_DIR).catch(() => []));
  const filesToWrite: Array<{ filename: string; content: string }> = [];

  for (const r of SEED) {
    const filename = `${r.slug}.md`;
    const full = path.join(OUT_DIR, filename);
    const fm = toFrontmatter(r);
    const body = [
      fm,
      "",
      `# ${r.title}`,
      "",
      r.description,
      "",
      "",
    ].join("\n");

    // do not overwrite user edits unless file is missing
    if (existing.has(filename)) continue;
    filesToWrite.push({ filename: full, content: body });
  }

  await Promise.all(filesToWrite.map((f) => fs.writeFile(f.filename, f.content, "utf8")));

  // small index file so the folder exists even if seed changes
  const metaPath = path.join(OUT_DIR, "_seed.json");
  await fs.writeFile(
    metaPath,
    JSON.stringify({ generatedAt: new Date().toISOString(), count: SEED.length }, null, 2) + "\n",
    "utf8",
  );

  const written = filesToWrite.length;
  console.log(`OK: resources dir: ${OUT_DIR}`);
  console.log(`OK: seed entries: ${SEED.length}`);
  console.log(`OK: wrote new files: ${written}`);
  if (written === 0) console.log("Nota: no se sobreescribio nada (ya existian los archivos).");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});

